export enum CircleTransactionStatus {
  INITIATED = 'INITIATED',
  PENDING_RISK_SCREENING = 'PENDING_RISK_SCREENING',
  DENIED = 'DENIED',
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  CONFIRMED = 'CONFIRMED',
  COMPLETE = 'COMPLETE',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
